name: Post latest data

on:
  schedule:
    - cron: '0 9-22 * * *'
  workflow_dispatch:
jobs:
  post_latest_data:
    name: Post latest data to historic db
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl -X POST -d {} https://argentinavacunada.vercel.app/api/historic_data
