name: Post latest data every hour

on:
  schedule:
    - cron: '0 10-23 * * *'
jobs:
  post_latest_data:
    name: Post latest data to historic db
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: curl -X POST -d {} https://argentinavacunada.vercel.app/api/historic_data
